server:
  port: 7002
#服务名称
spring:
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource #当前数据的操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.113:3306/db2019  #?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

