server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    ga
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
